

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Wenhou Lu
 */
public class MainFrame extends javax.swing.JFrame {

    private boolean showSubMenu = true;
    private SubMenu1Panel subMenu;

    /**
     * Creates new form Dashboard
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        buttonDashboard = new javax.swing.JButton();
        buttonMining = new javax.swing.JButton();
        buttonImport = new javax.swing.JButton();
        buttonAWS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        buttonCharts = new javax.swing.JButton();
        buttonExit1 = new javax.swing.JButton();
        panelBanner = new javax.swing.JPanel();
        panelMain = new javax.swing.JPanel();
        panelSubMenu2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Analytics System");

        panelBackground.setBackground(new java.awt.Color(242, 240, 241));

        panelMenu.setBackground(new java.awt.Color(47, 61, 76));

        buttonDashboard.setBackground(new java.awt.Color(40, 54, 65));
        buttonDashboard.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonDashboard.setForeground(new java.awt.Color(255, 255, 255));
        buttonDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N
        buttonDashboard.setText(" DASHBOARD  ");
        buttonDashboard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDashboard.setPreferredSize(new java.awt.Dimension(127, 39));
        buttonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDashboardActionPerformed(evt);
            }
        });

        buttonMining.setBackground(new java.awt.Color(40, 54, 65));
        buttonMining.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonMining.setForeground(new java.awt.Color(255, 255, 255));
        buttonMining.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/data_mining.png"))); // NOI18N
        buttonMining.setText(" DATA MINING");
        buttonMining.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonMining.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonMining.setPreferredSize(new java.awt.Dimension(127, 39));
        buttonMining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMiningActionPerformed(evt);
            }
        });

        buttonImport.setBackground(new java.awt.Color(40, 54, 65));
        buttonImport.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonImport.setForeground(new java.awt.Color(255, 255, 255));
        buttonImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download.png"))); // NOI18N
        buttonImport.setText(" IMPORT");
        buttonImport.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonImport.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonImport.setPreferredSize(new java.awt.Dimension(127, 39));
        buttonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportActionPerformed(evt);
            }
        });

        buttonAWS.setBackground(new java.awt.Color(40, 54, 65));
        buttonAWS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonAWS.setForeground(new java.awt.Color(255, 255, 255));
        buttonAWS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/upload.png"))); // NOI18N
        buttonAWS.setText(" AWS");
        buttonAWS.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonAWS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonAWS.setPreferredSize(new java.awt.Dimension(127, 39));
        buttonAWS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAWSActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");

        buttonExit.setBackground(new java.awt.Color(40, 54, 65));
        buttonExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        buttonExit.setText(" EXIT");
        buttonExit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonExit.setPreferredSize(new java.awt.Dimension(127, 39));
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonCharts.setBackground(new java.awt.Color(40, 54, 65));
        buttonCharts.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonCharts.setForeground(new java.awt.Color(255, 255, 255));
        buttonCharts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/charts.png"))); // NOI18N
        buttonCharts.setText(" CHARTS");
        buttonCharts.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonCharts.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonCharts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChartsActionPerformed(evt);
            }
        });

        buttonExit1.setBackground(new java.awt.Color(40, 54, 65));
        buttonExit1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonExit1.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/settings.png"))); // NOI18N
        buttonExit1.setText(" SETTINGS");
        buttonExit1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonExit1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonExit1.setPreferredSize(new java.awt.Dimension(127, 39));
        buttonExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
            .addComponent(buttonImport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(buttonCharts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonMining, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonAWS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonExit1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(buttonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonMining, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonCharts, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonImport, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonAWS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelBanner.setBackground(new java.awt.Color(153, 153, 153));
        panelBanner.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelBannerLayout = new javax.swing.GroupLayout(panelBanner);
        panelBanner.setLayout(panelBannerLayout);
        panelBannerLayout.setHorizontalGroup(
            panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelBannerLayout.setVerticalGroup(
            panelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
        );

        panelMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panelSubMenu2Layout = new javax.swing.GroupLayout(panelSubMenu2);
        panelSubMenu2.setLayout(panelSubMenu2Layout);
        panelSubMenu2Layout.setHorizontalGroup(
            panelSubMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        panelSubMenu2Layout.setVerticalGroup(
            panelSubMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSubMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSubMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addComponent(panelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDashboardActionPerformed

    private void buttonMiningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMiningActionPerformed
        // TODO add your handling code here:
        subMenu = new SubMenu1Panel();
        if (showSubMenu) {
            panelMain.add(subMenu);
            showSubMenu = false;
        } else {
            panelMain.remove(subMenu);
            showSubMenu = true;
        }
    }//GEN-LAST:event_buttonMiningActionPerformed

    private void buttonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImportActionPerformed
        // TODO add your handling code here:
        ImportPanel import1 = new ImportPanel();
        panelMain.add(import1);
        import1.validate();
        import1.setLocation(0, 0);
        //import1.setVisible(true);
        panelMain.repaint();
    }//GEN-LAST:event_buttonImportActionPerformed

    private void buttonAWSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAWSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAWSActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonChartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChartsActionPerformed
        // TODO add your handling code here:
        subMenu = new SubMenu1Panel();
        if (showSubMenu) {
            panelMain.add(subMenu);
            System.out.println(buttonCharts.getLocation());
            subMenu.setLocation(128, 196);
            panelMain.validate();
            panelMain.repaint();
            System.out.println(subMenu.getLocation());
            showSubMenu = false;
            System.out.println(panelMain.contains(28,196));
        } else {
            panelMain.remove(subMenu);
            showSubMenu = true;
        }
    }//GEN-LAST:event_buttonChartsActionPerformed

    private void buttonExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExit1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAWS;
    private javax.swing.JButton buttonCharts;
    private javax.swing.JButton buttonDashboard;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonExit1;
    private javax.swing.JButton buttonImport;
    private javax.swing.JButton buttonMining;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBanner;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSubMenu2;
    // End of variables declaration//GEN-END:variables
}
