/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Wenhou Lu
 */
public class SubMenu2Panel extends javax.swing.JPanel {

    /**
     * Creates new form SubMenu2Panel
     */
    public SubMenu2Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRegression = new javax.swing.JButton();
        buttonCluster = new javax.swing.JButton();

        buttonRegression.setBackground(new java.awt.Color(40, 54, 65));
        buttonRegression.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonRegression.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegression.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/line_chart.png"))); // NOI18N
        buttonRegression.setText(" REGRESSION");
        buttonRegression.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonRegression.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonRegression.setName(""); // NOI18N
        buttonRegression.setPreferredSize(new java.awt.Dimension(127, 39));
        buttonRegression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegressionActionPerformed(evt);
            }
        });

        buttonCluster.setBackground(new java.awt.Color(40, 54, 65));
        buttonCluster.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonCluster.setForeground(new java.awt.Color(255, 255, 255));
        buttonCluster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/column_chart.png"))); // NOI18N
        buttonCluster.setText(" CLUSTER");
        buttonCluster.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        buttonCluster.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonCluster.setMaximumSize(new java.awt.Dimension(115, 45));
        buttonCluster.setMinimumSize(new java.awt.Dimension(115, 45));
        buttonCluster.setPreferredSize(new java.awt.Dimension(127, 39));
        buttonCluster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClusterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonRegression, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
            .addComponent(buttonCluster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonCluster, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonRegression, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegressionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegressionActionPerformed

    private void buttonClusterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClusterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonClusterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCluster;
    private javax.swing.JButton buttonRegression;
    // End of variables declaration//GEN-END:variables
}
